test: modify Java test code
naver/scavenger pull request #46
Opened 2023-03-07 12:42 UTC by hyeok7777

- Fixed some variable names in file ConfigUtilsTest.java that do not conform to the Java naming convention
- Remove unnecessary public

2023-03-08 08:15 UTC, junoyoon commented
@hyeok7777 
Thx for contribution.
One thing I noticed is that blarBlar_BlarBlar is out internal convention(undocumented yet) to describe the test condition.
Please make test method name keep this convention plz

2023-03-08 08:16 UTC, junoyoon requested changes
Thx for contribution.
One thing I noticed is that blarBlar_BlarBlar is out internal convention(undocumented yet) to describe the test condition.
Please make test method name keep this convention plz

2023-03-10 02:38 UTC, junoyoon commented
@hyeok7777 please check my comment

2023-03-10 02:39 UTC, junoyoon commented on scavenger-agent-java/src/test/java/com/navercorp/scavenger/javaagent/util/ConfigUtilsTest.java
> +            void expandVariablesWithBraces() {
```suggestion
            void expandVariables_with_braces() {
```

2023-03-11 05:12 UTC, hyeok7777 commented
@junoyoon 
Forgive me for being late. I modified and committed what you said.

2023-03-11 05:40 UTC, taeyeon-Kim approved these changes
thx

2023-03-11 05:43 UTC, kojandy approved these changes

2023-03-11 16:58 UTC, junoyoon commented
이번 건은 외부 fork 로 부터 PR 이라.. merge commit 이 들어왔습니다. 
어쩔수 없이, 이번엔 허용합니다.

2023-03-11 16:58 UTC, merged